(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&c(o)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const f=document.querySelector(".mobile-menu"),l=document.querySelector(".menu-btn-open"),a=document.querySelector(".menu-btn-close"),u=()=>f.classList.toggle("is-open"),m=()=>document.body.classList.toggle("is-scroll-disabled");l.addEventListener("click",u);a.addEventListener("click",u);l.addEventListener("click",m);a.addEventListener("click",m);document.addEventListener("DOMContentLoaded",()=>{const r=document.documentElement;let e=null;const s=window.matchMedia("(min-width: 320px)");function c(){if(e)return;e=document.createElement("button"),e.className="theme-toggle",e.type="button",e.setAttribute("aria-label","Toggle theme"),e.innerHTML=`
      <div class="icon-wrapper" aria-hidden="true">
        <svg class="icon sun" viewBox="0 0 24 24">
          <path d="M12 4V2m0 20v-2m8-8h2M2 12h2m14.14 5.14l1.42 1.42M4.44 4.44l1.42 1.42m12.28 0l1.42-1.42M4.44 19.56l1.42-1.42M12 6a6 6 0 100 12 6 6 0 000-12z" fill="currentColor"/>
        </svg>
        <svg class="icon moon" viewBox="0 0 24 24">
          <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z" fill="currentColor"/>
        </svg>
      </div>
    `;const o=localStorage.getItem("theme");if(o)r.setAttribute("data-theme",o);else{const i=window.matchMedia("(prefers-color-scheme: dark)").matches;r.setAttribute("data-theme",i?"dark":"light")}e.addEventListener("click",()=>{const d=r.getAttribute("data-theme")==="dark"?"light":"dark";r.setAttribute("data-theme",d),localStorage.setItem("theme",d)}),document.body.appendChild(e)}function t(){e&&(e.remove(),e=null)}s.matches?c():t();const n=o=>o.matches?c():t();s.addEventListener?s.addEventListener("change",n):s.addListener(n)});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".sub-form"),e=document.querySelector(".modal-backdrop"),s=e==null?void 0:e.querySelector(".close-btn-backdrop"),c=e==null?void 0:e.querySelector(".modal-button");if(!e||!r)return;const t=()=>{e.classList.add("subscription-open"),document.body.style.overflow="hidden"},n=()=>{e.classList.remove("subscription-open"),document.body.style.overflow=""};r.addEventListener("submit",o=>{o.preventDefault(),t(),r.reset()}),s==null||s.addEventListener("click",n),c==null||c.addEventListener("click",n),e.addEventListener("click",o=>{o.target===e&&n()}),document.addEventListener("keydown",o=>{o.key==="Escape"&&n()})});window.innerWidth>=1440&&window.addEventListener("wheel",r=>{r.preventDefault(),window.scrollBy({top:r.deltaY*.7,behavior:"smooth"})},{passive:!1});
//# sourceMappingURL=index.js.map
